apiVersion: v1
kind: Service
metadata:
  name: erigon
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

spec:
  ports:
  - name: peers
    port: 30303
    targetPort: 30303
    protocol: TCP

  - name: snapsync
    port: 42069
    targetPort: 42069
    protocol: TCP

  # - name: peers-udp
  #   port: 30303
  #   targetPort: 30303
  #   protocol: UDP

  # - name: snapsync-udp
  #   port: 42069
  #   targetPort: 42069
  #   protocol: UDP

  selector:
    name: erigon
    app.kubernetes.io/part-of: erigon
  type: LoadBalancer
