apiVersion: v1
kind: Pod
metadata:
  name: task-pv-erigon
spec:
  volumes:
    - name: openebs-zfspv
      persistentVolumeClaim:
        claimName: csi-zfspv
  containers:
    - name: erigon-container
      image: avi17/erigon
      volumeMounts:
        - mountPath: "/erigon/"
          name: openebs-zfspv
      args: ["--downloader.verify","--datadir=/erigon/","--private.api.addr=localhost:9090","--chain","mainnet","--healthcheck","--http=true","--http.addr='0.0.0.0'","--http.vhosts='*'","--http.api=eth,erigon,web3,net,debug,trace,txpool","--ws","--ws.compression"]
      command: ["erigon"]
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  #   runAsGroup: 1000   
