apiVersion: v1
kind: Pod
metadata:
  name: erigon
  labels:
    app.kubernetes.io/part-of: erigon
spec:
  restartPolicy: Always
  hostNetwork: true

  containers:
  - name: erigon-container
    image: avi17/erigon:v2.28.1
    command: ["erigon"]
    args: ["--downloader.verify","--datadir=/erigon/","--private.api.addr=localhost:9090","--chain","mainnet","--healthcheck","--http=true","--http.addr='0.0.0.0'","--http.vhosts='*'","--http.api=eth,erigon,web3,net,debug,trace,txpool","--ws","--ws.compression"]
    volumeMounts:
       - mountPath: /erigon/
         name: openebs-zfspv
    tty: true
    ports:
    - name: peers
      containerPort: 30303
      # targetPort: 30303
      protocol: TCP

    - name: snapsync
      containerPort: 42069
      # targetPort: 30303
      protocol: TCP

    - name: peers-udp
      containerPort: 30303
      protocol: UDP

    - name: snapsync-udp
      containerPort: 42069
      protocol: UDP

  volumes:
  - name: openebs-zfspv
    persistentVolumeClaim:
      claimName: csi-zfspv